#!/usr/bin/env python3
"""Regenerate the `docker run` commands of STANDALONE containers (not managed by
compose) from the `docker inspect` dump saved by the global backup.
Usage: gen-docker-run.py containers-inspect.json > recreate.sh ; review it, then run it."""
import json, shlex, sys

def main(path):
    data = json.load(open(path))
    print("#!/usr/bin/env bash\n# Generated by gen-docker-run.py. REVIEW before running.\nset -e")
    for c in data:
        cfg, hc = c.get("Config", {}), c.get("HostConfig", {})
        labels = cfg.get("Labels") or {}
        name = c.get("Name", "").lstrip("/")
        if any(k.startswith("com.docker.compose") for k in labels):
            print(f"# {name}: managed by compose ({labels.get('com.docker.compose.project')}), use docker compose up -d")
            continue
        args = ["docker", "run", "-d", "--name", name]
        rp = (hc.get("RestartPolicy") or {}).get("Name")
        if rp and rp != "no":
            args += ["--restart", rp]
        for e in cfg.get("Env") or []:
            if e.startswith("PATH=") or e.startswith("HOME=") or e.startswith("NODE_VERSION=") or e.startswith("YARN_VERSION="):
                continue
            args += ["-e", e]
        for port, binds in (hc.get("PortBindings") or {}).items():
            for b in binds or []:
                ip = b.get("HostIp") or ""
                hp = b.get("HostPort") or ""
                args += ["-p", f"{ip + ':' if ip else ''}{hp}:{port.split('/')[0]}"]
        for m in c.get("Mounts") or []:
            src = m.get("Name") if m.get("Type") == "volume" else m.get("Source")
            ro = "" if m.get("RW", True) else ":ro"
            args += ["-v", f"{src}:{m.get('Destination')}{ro}"]
        if hc.get("Memory"):
            args += ["--memory", str(hc["Memory"])]
        if hc.get("NanoCpus"):
            args += ["--cpus", str(hc["NanoCpus"] / 1e9)]
        nets = list(((c.get("NetworkSettings") or {}).get("Networks") or {}).keys())
        if nets:
            args += ["--network", nets[0]]
        for k, v in labels.items():
            if k.startswith("org.opencontainers."):
                continue  # labels inherited from the image, must not be re-passed
            args += ["--label", f"{k}={v}"]
        if hc.get("Init"):
            args += ["--init"]
        image = cfg.get("Image") or c.get("Image")
        ver = labels.get("org.opencontainers.image.version", "?")
        print(f"# {name}: original image {image} (version {ver}, id {c.get('Image','')[:19]}). "
              f"If the tag is :latest, consider pinning :{ver} to keep the same version.")
        args.append(image)
        cmd = cfg.get("Cmd")
        if cmd and cfg.get("Entrypoint") is None:
            args += cmd
        print(" ".join(shlex.quote(a) for a in args))
        for n in nets[1:]:
            print(f"docker network connect {shlex.quote(n)} {shlex.quote(name)}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__); sys.exit(2)
    main(sys.argv[1])
